# config.yml

backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
media_folder: 'assets'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
  - name: 'about'
    label: 'about'
    files:
      - label: "About us"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: About
            name: about
            widget: list
            fields: 
              - {label: About, name: about, widget: string}
  - name: 'residents'
    label: 'Residents'
    files:
      - label: "Residents"
        name: "resident"
        file: "_data/residents.yml"
        fields:
          - label: Residents
            name: residents
            widget: list
            fields: 
              - {label: Residents, name: resident, widget: string}
  


