# config.yml

backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
media_folder: 'assets'
collections:
  - name: 'about'
    label: 'About'
    files:
      - label: "About us"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: About
            name: about
            widget: list
            fields: 
              - {label: About, name: about, widget: markdown}
              - {label: title, name: title, widget: string}
              - {label: Sub-title, name: sub_title, widget: string}

  - name: 'residents'
    label: 'Residents'
    files:
      - label: "Residents"
        name: "resident"
        file: "_data/residents.yml"
        fields:
          - label: Residents
            name: residents
            widget: list
            fields: 
              - {label: Residents, name: resident, widget: markdown}
  
  - name: 'health_professionals'
    label: 'Health Professionals'
    files:
      - label: "Health Professionals"
        name: "health_professionals"
        file: "_data/health_professionals.yml"
        fields:
          - label: "Health Professionals"
            name: health_professionals
            widget: list
            fields: 
              - {label: Sub-title, name: sub_title, widget: string}
              - {label: Description, name: description, widget: markdown}

  - name: 'home_page'
    label: 'Home Page'
    files:
      - label: "Home Page"
        name: "home_page"
        file: "_data/home_page.yml"
        fields:
          - label: "Home Page"
            name: home_page
            widget: list
            fields: 
              - {label: Sub-title, name: welcome_sub_title, widget: string}
              - {label: Title, name: welcome_title, widget: string}
              - {label: 'Organization Goal', name: organization_goal, widget: string}

  - name: 'referral_tile_one'
    label: 'Referral to link Workers'
    files:
      - label: "Referral to link Workers"
        name: "referral_tile_one"
        file: "_data/referral_tile_one.yml"
        fields:
          - label: "Referral to link Workers"
            name: referral_tile_one
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'referral_tile_four'
    label: 'Referral Four'
    files:
      - label: "Referral Four"
        name: "referral_tile_four"
        file: "_data/referral_tile_four.yml"
        fields:
          - label: "Referral Four"
            name: referral_tile_four
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'referral_tile_three'
    label: 'Referral for Long term conditions'
    files:
      - label: "Referral for Long term conditions"
        name: "referral_tile_three"
        file: "_data/referral_tile_three.yml"
        fields:
          - label: "Referral for Long term conditions"
            name: referral_tile_three
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'referral_tile_two'
    label: 'Referral for mental health'
    files:
      - label: "Referral for mental health"
        name: "referral_tile_two"
        file: "_data/referral_tile_two.yml"
        fields:
          - label: "Referral for mental health"
            name: referral_tile_two
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'referral_tile_five'
    label: 'Self care services'
    files:
      - label: "Self care services"
        name: "referral_tile_five"
        file: "_data/referral_tile_five.yml"
        fields:
          - label: "Self care services"
            name: referral_tile_five
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'referral_tile_six'
    label: 'Referral to Nth Ken'
    files:
      - label: "Referral to Nth Ken"
        name: "referral_tile_six"
        file: "_data/referral_tile_six.yml"
        fields:
          - label: "Referral to Nth Ken"
            name: referral_tile_six
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'kcsc_directory'
    label: 'KCSC Directory'
    files:
      - label: "KCSC Directory"
        name: "kcsc_directory"
        file: "_data/kcsc_directory.yml"
        fields:
          - label: "KCSC Directory"
            name: kcsc_directory
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'residents_tile_extra_0'
    label: 'Residents tile extra'
    files:
      - label: "Residents tile extra"
        name: "residents_tile_extra_0"
        file: "_data/residents_tile_extra_0.yml"
        fields:
          - label: "Residents tile extra"
            name: residents_tile_extra_0
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'residents_tile_extra_1'
    label: 'Residents tile extra 1'
    files:
      - label: "Residents tile extra 1"
        name: "residents_tile_extra_1"
        file: "_data/residents_tile_extra_1.yml"
        fields:
          - label: "KCSC Directory"
            name: residents_tile_extra_1
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'residents_tile_extra_2'
    label: 'Residents tile extra 2'
    files:
      - label: "Residents tile extra 2"
        name: "residents_tile_extra_2"
        file: "_data/residents_tile_extra_2.yml"
        fields:
          - label: "Extra Tile 2"
            name: residents_tile_extra_2
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'residents_tile_extra_3'
    label: 'Residents tile extra 3'
    files:
      - label: "Residents tile extra 3"
        name: "residents_tile_extra_3"
        file: "_data/residents_tile_extra_3.yml"
        fields:
          - label: "Extra tile 3"
            name: residents_tile_extra_3
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'residents_tile_extra_4'
    label: 'Residents tile extra 4'
    files:
      - label: "Residents tile extra 4"
        name: "residents_tile_extra_4"
        file: "_data/residents_tile_extra_4.yml"
        fields:
          - label: "Extra tile 4"
            name: residents_tile_extra_4
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Text, name: text, widget: string}

  - name: 'subscribe'
    label: 'Subscribe'
    files:
      - label: "Subscribe"
        name: "subscribe"
        file: "_data/subscribe.yml"
        fields:
          - label: "Subscribe"
            name: subscribe
            widget: list
            fields: 
              - {label: Text, name: text, widget: string}

  - name: 'contacts'
    label: 'Contacts'
    files:
      - label: "Contacts"
        name: "contacts"
        file: "_data/contacts.yml"
        fields:
          - label: "Contacts"
            name: contacts
            widget: list
            fields: 
              - {label: Address, name: address, widget: string}
              - {label: Telephone, name: telephone, widget: string}
              - {label: Email, name: email, widget: string}
              - {label: About-Summary, name: about, widget: string}

  - name: 'partners'
    label: 'Our Partners'
    files:
      - label: 'Our Partners'
        name: 'partners'
        file: '_data/partners.yml'
        fields:
          - label: 'Our partners'
            name: partners
            widget: list
            fields: 
              - {label: Partners, name: text, widget: markdown}
  
  - name: 'extra_page'
    label: 'Extra Page'
    files:
      - label: 'Extra Page'
        name: 'extra_page'
        file: '_data/extra_page.yml'
        fields:
          - label: 'Extra Page'
            name: extra_page
            widget: list
            fields: 
              - {label: "Display", name: "display", widget: "boolean", default: false}
              - {label: "Title", name: "title", widget: "string"}

  - name: 'extra_page_content'
    label: 'Extra Page'
    files:
      - label: 'Extra Page'
        name: 'extra_page'
        file: '_data/extra_page.yml'
        fields:
          - label: 'Extra Page'
            name: extra_page
            widget: list
            fields: 
              - {label: "text", name: "display", widget: "markdown"}


  - name: 'news_article_one'
    label: 'News Article One'
    files:
      - label: 'News Article One'
        name: 'news_article_one'
        file: '_data/news_article_one.yml'
        fields:
          - label: 'News Article One'
            name: news_article_one
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Date published", name: "date_published", widget: "text"}
              - {label: "Author", name: "author", widget: "text"}
              - {label: "About author", name: "about_author", widget: "text"}
              - {label: "Text", name: "text", widget: "markdown"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}

  - name: 'news_article_two'
    label: 'News Article Two'
    files:
      - label: 'News Article Two'
        name: 'news_article_two'
        file: '_data/news_article_two.yml'
        fields:
          - label: 'News Article Two'
            name: news_article_two
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Date published", name: "date_published", widget: "text"}
              - {label: "Author", name: "author", widget: "text"}
              - {label: "About author", name: "about_author", widget: "text"}
              - {label: "Text", name: "text", widget: "markdown"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}

  - name: 'news_article_three'
    label: 'News Article Three'
    files:
      - label: 'News Article Three'
        name: 'news_article_three'
        file: '_data/news_article_three.yml'
        fields:
          - label: 'News Article Three'
            name: news_article_three
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Date published", name: "date_published", widget: "text"}
              - {label: "Author", name: "author", widget: "text"}
              - {label: "About author", name: "about_author", widget: "text"}
              - {label: "Text", name: "text", widget: "markdown"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}

  - name: 'news_article_four'
    label: 'News Article Four'
    files:
      - label: 'News Article Four'
        name: 'news_article_four'
        file: '_data/news_article_four.yml'
        fields:
          - label: 'News Article Four'
            name: news_article_four
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Date published", name: "date_published", widget: "text"}
              - {label: "Author", name: "author", widget: "text"}
              - {label: "About author", name: "about_author", widget: "text"}
              - {label: "Text", name: "text", widget: "markdown"}
              - {label: "Subtitle", name: "subtitle", widget: "text"}

  - name: 'news_summaries'
    label: 'News Summaries'
    files:
      - label: 'News Summaries'
        name: 'news_summaries'
        file: '_data/news_summaries.yml'
        fields:
          - label: 'News Summaries'
            name: news_summaries
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Date published", name: "date_published", widget: "text"}
              - {label: "Author", name: "author", widget: "text"}
              - {label: "Links To", name: "links_to", widget: "text"}
              - {label: "Summary", name: "summary", widget: "markdown"}
              - {label: "Is displayable", name: "is_displayable", widget: "boolean"}

  - name: 'kcsc_directory_page'
    label: 'KCSC Directory Page content'
    files:
      - label: 'KCSC Directory Page content'
        name: 'kcsc_directory_page'
        file: '_data/kcsc_directory_page.yml'
        fields:
          - label: 'Helper Text'
            name: helper_text
            widget: list
            fields: 
              - {label: "Helper Text", name: "helper_text", widget: "text"}


  - name: 'partner_age_uk'
    label: 'Partner Age UK'
    files:
      - label: 'Age UK'
        name: 'partner_age_uk'
        file: '_data/partner_age_uk.yml'
        fields:
          - label: 'Age UK'
            name: partner_age_uk
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Sub-Title", name: "sub_title", widget: "text"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Display Facebook", name: "display_facebook", widget: "boolean"}
              - {label: "Facebook Link", name: "facebook_link", widget: "text"}
              - {label: "Display Instagram", name: "display_instagram", widget: "boolean"}
              - {label: "Instagram Link", name: "instagram_link", widget: "text"}
              - {label: "Display Twitter", name: "display_twitter", widget: "boolean"}
              - {label: "Twitter Link", name: "twitter_link", widget: "text"}

  - name: 'partner_bme'
    label: 'Partner BME'
    files:
      - label: 'BME'
        name: 'partner_bme'
        file: '_data/partner_bme.yml'
        fields:
          - label: 'BME'
            name: partner_bme
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Sub-Title", name: "sub_title", widget: "text"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Display Facebook", name: "display_facebook", widget: "boolean"}
              - {label: "Facebook Link", name: "facebook_link", widget: "text"}
              - {label: "Display Instagram", name: "display_instagram", widget: "boolean"}
              - {label: "Instagram Link", name: "instagram_link", widget: "text"}
              - {label: "Display Twitter", name: "display_twitter", widget: "boolean"}
              - {label: "Twitter Link", name: "twitter_link", widget: "text"}

  - name: 'partner_kcsc'
    label: 'Partner KCSC'
    files:
      - label: 'KCSC'
        name: 'partner_kcsc'
        file: '_data/partner_kcsc.yml'
        fields:
          - label: 'KCSC'
            name: partner_kcsc
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Sub-Title", name: "sub_title", widget: "text"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Display Facebook", name: "display_facebook", widget: "boolean"}
              - {label: "Facebook Link", name: "facebook_link", widget: "text"}
              - {label: "Display Instagram", name: "display_instagram", widget: "boolean"}
              - {label: "Instagram Link", name: "instagram_link", widget: "text"}
              - {label: "Display Twitter", name: "display_twitter", widget: "boolean"}
              - {label: "Twitter Link", name: "twitter_link", widget: "text"}

  - name: 'partner_one_westmister'
    label: 'Partner One Westmister'
    files:
      - label: 'One Westmister'
        name: 'partner_one_westmister'
        file: '_data/partner_one_westmister.yml'
        fields:
          - label: 'One Westmister'
            name: partner_one_westmister
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Sub-Title", name: "sub_title", widget: "text"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Display Facebook", name: "display_facebook", widget: "boolean"}
              - {label: "Facebook Link", name: "facebook_link", widget: "text"}
              - {label: "Display Instagram", name: "display_instagram", widget: "boolean"}
              - {label: "Instagram Link", name: "instagram_link", widget: "text"}
              - {label: "Display Twitter", name: "display_twitter", widget: "boolean"}
              - {label: "Twitter Link", name: "twitter_link", widget: "text"}

  - name: 'partner_open_age'
    label: 'Partner Open Age'
    files:
      - label: 'Open Age'
        name: 'partner_open_age'
        file: '_data/partner_open_age.yml'
        fields:
          - label: 'Open Age'
            name: partner_open_age
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Sub-Title", name: "sub_title", widget: "text"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Display Facebook", name: "display_facebook", widget: "boolean"}
              - {label: "Facebook Link", name: "facebook_link", widget: "text"}
              - {label: "Display Instagram", name: "display_instagram", widget: "boolean"}
              - {label: "Instagram Link", name: "instagram_link", widget: "text"}
              - {label: "Display Twitter", name: "display_twitter", widget: "boolean"}
              - {label: "Twitter Link", name: "twitter_link", widget: "text"}

  - name: 'partner_smart'
    label: 'Partner SMART'
    files:
      - label: 'SMART'
        name: 'partner_smart'
        file: '_data/partner_smart.yml'
        fields:
          - label: 'SMART'
            name: partner_smart
            widget: list
            fields: 
              - {label: "Title", name: "title", widget: "text"}
              - {label: "Sub-Title", name: "sub_title", widget: "text"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Display Facebook", name: "display_facebook", widget: "boolean"}
              - {label: "Facebook Link", name: "facebook_link", widget: "text"}
              - {label: "Display Instagram", name: "display_instagram", widget: "boolean"}
              - {label: "Instagram Link", name: "instagram_link", widget: "text"}
              - {label: "Display Twitter", name: "display_twitter", widget: "boolean"}
              - {label: "Twitter Link", name: "twitter_link", widget: "text"}